### ISSUE TITLE
Issue with installing Jito on already working RPC Node

### ISSUE THREAD

**Issue by prezesov** [web3validator/solana_useful#5]
Hi. Could you please contact me on telegram:  https://t.me/pR3zes89
I have issue which I can not solve, or maybe you can send me your contact. I will highly appreciate it.

**Comment by web3validator** [comment]
which issue do you have?

**Comment by prezesov** [comment]
After reboot it still uses official 1.17.27 SolanaLab files instead of
Jito. I also looking for someone who can set up private validator for me
and connect it to my private node rpc. Do you have such a skills?
